language: python
python:
- '3.7'
before_install:
- pip install poetry
install:
- poetry install -v
- pip install tox-travis
script:
- tox
before_deploy:
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
- poetry build
deploy:
  provider: script
  script: poetry publish

env:
  global:
  - secure: DR9J5TQLVNXFILfpGWaEZeJYgFu0EDeHrZ4GUFdky4uziqPDrBEKBtZ78DXiO+PPDXN+sVHp/37/7D3wB+mUr4Ff/H5tfznTvhG6kEU16YMPUUCSro3TRGbRTsYcuVAxRJxOMuWp6TOYAn2/Yrj0SIs1teo0K/LLZ6/k5JRy1AJ+u8Dy3UwFUVbAX5xMurAXjpVoswMmSPMH694a7t+9gurtxpltypcX4q2EpHgQAsjyeGG0tCo2E65x4wo1lbOh/NPZ40fuwbhalrLBGsH3+yZh3cKAArsuk1b5b0V9mriqFxkZSE8fhtps0xLYLGbDo7mET0z9ZqF6INza+2Uo6oiAPhqnVE5vqCsrEQPW1gyc/TWpkzbP2sb8PD66r1CSuAzUgg6TJcN0RHOJSzg95enrp+w/15HdPFiAatS6pNUts1iQD7AhYyDH/z6rpOT0jD90WyOSTEpWDdaZ4uk2csLY1bheh0HgwgPosukJ163PtLOT/TZdy/W8vucb0H+W84jWIj5gBYzFmYF9A37AoBdnpIDkkLrkdqP/whURMLCRNPsF8bIWu5eml1+cqZmcEA0fPd02M5eEVsEnLU7yyg7b9ERfsvswVZsZ+rv2hlvxtWwwQWAk8oNacADfTKjpm6vew+Rat8HobUg8jsmxUx/bW4WSs9VPPdipNgC4nzM=
  - secure: FTZ9H8uRUveMnhFPRBjZzw680Wo5HaPY8d01hlaXELHt+u4u3FkoTcIAuklO4yIVXtBGH4nCF5Oub29oPJGDd5kjx53HO+lfrg6dddv12JCz1vKFvM6onLrxWqbGGhCs9BMdLzkkKlLxjVUzKp9IixYlzwR2t7RFEE+GvN3skTqrv+UP/iIrb8RTngc0jYuPjp7wPgkscnCr7C69To83LL7yq5KP9nqw7DydWdZiMCPspwYncmxmkXX6fcL6+S7du3+6hKT3UN2+L+rcGvg2GmsrDMvi0gm9npgtsq7UdR0xoeElcTGYp6tYGNLU0AIVdumVnNZZTFYaOfBhr6o3HgAAituD6zAUiLu+roqOykNqXJFYQiz0yKr6OOmIUoG39UlyxgCeoaCv2IL5Y5MEvn5tv6AKOlpavdkbzoR7XrtwqSpXn4ykKJalMxVetTez/vJ5Ef9f57Y813LBp3Qouc6s3JGrZmY0Q/XcikWD51qz1niUjJC639SRQwmPvWgl3qUyutff2z4e1k64NY6y1mtSA4TW4sl3k4sj7mVfIsv6O/a8P/SklGeg7PMPcRLJu/O/Fal2PragxOpfDshPxIC9GOaZIgiS5v5P9ShRYTD9cmH2YRj0MPA3cH15JXK3kYgzFaGlCnrdLAcZdl2jRfq/qjohP3oRcQ5vXTeYYxw=
