language: python
python:
- '3.7'
before_install:
- pip install poetry
install:
- poetry install -v
- pip install tox-travis
script:
- tox
before_deploy:
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
- poetry build
deploy:
  provider: script
  script: poetry publish --build
  on:
    tags: true
    all_branches: true
env:
  global:
  - secure: IixahLJkL4DyJlBlFXDrlQbl7phiydkJwMdea6ob70Wb7bihqj4I45V92+v+dxpxcrcGC3xlIctnjH9+remBYIPFHTv/gEfRP75/ebmVpVOy24fO8ckTcDnjQTY6mL0MCCKIQCKPbmH++4IvDBvvWy+Vcmc/KTFx731CNillROJ2UI6Ip/WsvREePXzus/7x8xBqK+QkBV6J+MG8IIzh+hwatQ+4OB7a8ByMfADk8VYrPD5TfYBmcFribif4w2EUOmY/ADo4ZKJzjqnv99Li12QBh2GxgLJYJdSYHjx1cW7QnQ+N3vSzKT2fl0BYrA/hV8z3DBBVOelLgbfGx4vAxLXIWyrqO3O9ALLFYdLbn6PqsFd7MRp+Y14ooWHUhGGHdZddC7f88SUvZDdMKoevNVQ04ak7Psyy1u6X8+n7rJe5pWS+xQu/h/AFfl15TpnuvB9c5ALSd4dLQy4B0/+JrvXAaXd3DZaf1IOlOeGs6nj61YtuXrtrCgzUKqGHXvrLK3ECmwZ7yy+Uk5eYnw0uuI0GNSwj6cBHrnGoZRb3P0PhGc85wf+njddSn9McogYBKb5DARVrj5iC1QuM6R5ZrMhHWOLGqK2RmBB/kaZw89XzzNy7kArXQjGZUIsCIK+jw1/ycTAQKY3NQK+edF1teBMxYB7DAGards9rx2jrvg0=
  - secure: EgHpcelKJAJy9UVXwKxWXW0CdSoxlg6mCVat0i8lQsNl8/iqbBA5240cUyhbRbt6uUcx5Dfk4jkm3P08h10Sc+q0GdQYa7cyI4F7x8CORiMtYBDpr6jKDmm4mMxW3wZ5d5YEEr00d6bVFMzWC7WO/tUjNLvM0hPivtbs2plU6hDnKgdiIrIPMQam9Jv9QlqtaHA27/RG4ysfZV/AokbVNeD6Nq9sgLvXzAKjogQHifXag7VN+tmBih/bDWB8/UX1MTvLv4NOOgpfx6wAqc9ZrR7wNhIBL5NGIM7PxYNcrCg/Pt2j7cfJ/Sqi+MOWc033CXHJBK/wLG9rJHJ2U5NTd/mLqh8Jzi4bf19h2kAE5hAs5HaqAO/d2xwD9BqguSJWol+f6IRsWwxXbTug7ALvIrabkoF3IvDTE+YI+YyOnEvU2w5L3bTRJ8th1xNqvTSYid61GtKwyRUIir4AIlbYFcsIkIbMnwHHWLLTlZRyAATCf7goCMPGiIHwy21L8JMmFrEAuILdVQkDjQiI582XsvB+7xJyaxBnJtR3z/FjZzUIx/W4fqLAQIxJOgDDfQgzpXCq9gp5gRtFREHBmsy+RhQpES0SVmuXppjx+cVDAipFW2AwoHs/TKPb4GBT2ETQCT63sDgkNyIdJnKbiSO+g2a8sVU6Lw6gJtDxDaQOceA=
